# Generated by Django 5.0.6 on 2024-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待出行'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
